services:

  catalog:
    depends_on:
      - config-server
      - mongodb_catalog
      - rabbitmq
    image: openjdk:22-jdk
    volumes:
      - ${CATALOG_JAR_PATH}:/app/app.jar
    working_dir: /app
    command: [ "java", "-jar", "/app/app.jar" ]
    environment:
      - SPRING_PROFILES_ACTIVE=${DEV_PROFILE}
      - MICROSERVICE_NAME=${MICROSERVICE_CATALOG_NAME}
    ports:
      - 8083:8080
      - 35729:35729
      # - 5005:5005

  operation:
    depends_on:
      - config-server
      - mongodb_operation
      - rabbitmq
    image: openjdk:22-jdk
    volumes:
      - ${OPERATION_JAR_PATH}:/app/app.jar
    working_dir: /app
    command: [ "java", "-jar", "/app/app.jar" ]
    environment:
      - SPRING_PROFILES_ACTIVE=${DEV_PROFILE}
      - MICROSERVICE_NAME=${MICROSERVICE_OPERATION_NAME}
    ports:
      - 8081:8080
      - 35730:35729
      # - 5006:5005

  analysis:
    depends_on:
      - config-server
      - rabbitmq
    image: openjdk:22-jdk
    volumes:
      - ${ANALYSIS_JAR_PATH}:/app/app.jar
    working_dir: /app
    command: [ "java", "-jar", "/app/app.jar" ]
    environment:
      - SPRING_PROFILES_ACTIVE=${DEV_PROFILE}
      - MICROSERVICE_NAME=${MICROSERVICE_ANALYSIS_NAME}
    ports:
      - 8082:8080
      - 35731:35729
      - 5007:5005

  gateway:
    depends_on:
      - config-server
      - rabbitmq
    image: openjdk:22-jdk
    volumes:
      - ./gateway/target/gateway-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: [ "java", "-jar", "/app/app.jar" ]
    environment:
      - SPRING_PROFILES_ACTIVE=${DEV_PROFILE}
      - MICROSERVICE_NAME=${MICROSERVICE_GATEWAY_NAME}
    ports:
      - 8080:8080
      - 35732:35729
      - 5008:5005

  config-server:
    image: openjdk:22-jdk
    volumes:
      - ./config:/config
      - ./config-server/target/config-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: [ "java", "-jar", "/app/app.jar" ]
    ports:
      - "8888:8888"

  mongodb_catalog:
    image: 'mongo:latest'
    volumes:
      - ./catalog/mongodb_data:/data/db
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=myuser'
    ports:
      - 27017:27017

  mongodb_operation:
    image: 'mongo:latest'
    volumes:
      - ./operation/mongodb_data:/data/db
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=myuser'
    ports:
      - 27018:27017

  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672'
      - 15672:15672

volumes:
  rabbitmq_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  # mongodb_data:
  #   driver: local
  #   driver_opts:
  #     type: tmpfs
  #     device: tmpfs
