spring:
  data:
    mongodb:
      host: mongodb_analysis
      port: 27017
      database: mydatabase
      username: myuser
      password: secret

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret