spring:
  data:
    mongodb:
      host: mongodb_operation
      port: 27017
      database: mydatabase
      username: myuser
      password: secret

  # cloud:
  #     function:
  #       routing-expression: "headers['myroutekey']"
  #     stream:
  #       defaultBinder: rabbit
  #       output-bindings: catalog_in;operation_in
  #       bindings:
  #         functionRouter-in-0:
  #           destination: analysis_in
        

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret