spring:
  main:
    web-application-type: none

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
      authentication-database: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
    in-queue: catalog_in
