spring:
  data:
    mongodb:
      host: mongodb_catalog
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
      authentication-database: admin

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret
    in-queue: catalog_in