spring:
  data:
    mongodb:
      host: mongodb_catalog
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
      
  cloud:
      stream:
        defaultBinder: rabbit
        output-bindings: test-exchange
        # bindings:
        #   producer-out-0:
        #     destination: test-exchange
        #     group: my-group
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret