spring:
  data:
    mongodb:
      host: mongodb_catalog
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
  
  cloud:
      # function:
      #   routing-expression: headers['myroutekey']
      stream:
        defaultBinder: rabbit
        # function:
        #   routing:
        #     enabled: true
        output-bindings: operation_in;analysis_in
        # bindings:
        #   producer-out-0:
        #     destination: test-exchange
        #     group: my-group


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret