spring:
  data:
    mongodb:
      host: mongodb_catalog
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
  
  # cloud:
  #     function:
  #       routing-expression: headers['myroutekey']
  #     stream:
  #       defaultBinder: rabbit
  #       output-bindings: operation_in;analysis_in
  #       bindings:
  #         functionRouter-in-0:
  #           destination: catalog_in
  #         testConsumer1-in-0:
  #           destination: catalog_in2
  #           group: catalog
  #         testConsumer2-in-0:
  #           destination: catalog_in2
  #           group: catalog


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret