spring:
  data:
    mongodb:
      host: mongodb_catalog
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
      
  cloud:
    stream:
      # output-bindings: testexchange
      bindings:
        produceMessage-out-0:
          destination: testexchange
      # rabbit:
      #   bindings:
      #     produceMessage-out-0:
      #       producer:
      #         routingKeyExpression: headers['routingKey']

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret