spring:
  devtools:
    livereload:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
    in-queue: gateway_in
# logging:
#   level:
#     org.springframework.boot.devtools: DEBUG
