spring:
  main:
    web-application-type: none

  devtools:
    livereload:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: 27018
      database: mydatabase
      username: myuser
      password: secret
      authentication-database: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
    in-queue: operation_in
# logging:
#   level:
#     org.springframework.boot.devtools: DEBUG
