spring:
  main:
    web-application-type: none

  data:
    mongodb:
      host: mongodb_operation
      port: 27017
      database: mydatabase
      username: myuser
      password: secret
      authentication-database: admin

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret
    in-queue: operation_in
