spring:
  data:
    mongodb:
      host: mongodb_operation
      port: 27017
      database: mydatabase
      username: myuser
      password: secret

  cloud:
      stream:
        defaultBinder: rabbit
        bindings:
          consumer-in-0:
            destination: test-exchange
            group: my-group

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret