spring:
  data:
    mongodb:
      host: mongodb_operation
      port: 27017
      database: mydatabase
      username: myuser
      password: secret

  cloud:

      function:
        # routing-expression: "headers['myroutekey'] == 'consumerA' ? 'consumerA' : 'consumerB'"
        routing-expression: "headers['myroutekey']"
        # definition: consumerA;consumerB
      stream:
        defaultBinder: rabbit
        bindings:
          functionRouter-in-0:
            destination: operation_in
        #     # group: my-group
        #   consumerB-in-0:
        #     destination: functionRouter-in-0
        #     # group: my-group
        

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret