spring:
  data:
    mongodb:
      host: mongodb_operation
      port: 27017
      database: mydatabase
      username: myuser
      password: secret

  cloud:
    stream:
      bindings:
        consumeMessage-in-0:
          destination: testexchange
      # rabbit:
      #   bindings:
      #     consumeMessage-in-0:
      #       consumer:
      #         bindQueue: true
      #         declareExchange: false
      #         queueNameGroupOnly: true
      #         bindingRoutingKey: '#'  # Ricevi tutti i messaggi, puoi specificare routing key specifiche se necessario

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret